#############################################################################
# Makefile for building: buff
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Nov 17 23:57:14 2015
# Project:  buff.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile buff.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
LINK          = g++

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		RealStack.cpp 
OBJECTS       = main.o \
		RealStack.o
TARGET        = solution

all: $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS)

clean:
	$(RM) $(OBJECTS)
	$(RM) $(TARGET)

main.o: main.cpp RealStack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

RealStack.o: RealStack.cpp RealStack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RealStack.o RealStack.cpp
